version: '3.9'
services:
  chat_buddy:
    volumes:
      - .:/app

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file: .env
    volumes:
      - mongo-db:/data/db

  mongo-client:
    container_name: mongo-client
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: .env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo


volumes:
  mongo-db:
  node_modules: